version: '2.2'
services:
  server:
    build: .
    #image: ghcr.io/cheminfo/ocl-cache-docker:head
    restart: always
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
    ports:
      - 127.0.0.1:41210:41210

  import:
    build: .
    #image: ghcr.io/cheminfo/ocl-cache-docker:head
    restart: always
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
      - ./sync:/node/sync
      - ./cache:/node/cache
    command: npm run syncDev
